package com.bugenzhao.mnga.util

/** English string literal -> Android string resource name. */
object StringsMap {
    val map: Map<String, String> = mapOf(
        "Topics" to "topics",
        "Topic" to "topic",
        "Post" to "post",
        "Replies" to "replies",
        "Post/Reply" to "post_reply",
        "Subforums" to "subforums",
        "Subforums (%lld)" to "subforums_d",
        "Refresh" to "refresh",
        "Copy Raw Content" to "copy_raw_content",
        "Reply" to "reply",
        "Forums" to "forums",
        "Latest Topics" to "latest_topics",
        "Favorites" to "favorites",
        "No Favorites" to "no_favorites",
        "No Results" to "no_results",
        "Remove from Favorites" to "remove_from_favorites",
        "Mark as Favorite" to "mark_as_favorite",
        "Favorite in..." to "favorite_in",
        "Favorites Only" to "favorites_only",
        "All Forums" to "all_forums",
        "Search Forums" to "search_forums",
        "Sign In" to "sign_in",
        "Agreement" to "agreement",
        "Privacy" to "privacy",
        "Sign Out" to "sign_out",
        "Me" to "me",
        "%u Posts" to "u_posts",
        "Sign in to NGA" to "sign_in_to_nga",
        "From NGA" to "from_nga",
        "Cancel" to "cancel",
        "Subforums of %@" to "subforums_of_s",
        "History" to "history",
        "No History" to "no_history",
        "Hot Topics" to "hot_topics",
        "Last 24 hours" to "last_24_hours",
        "Last week" to "last_week",
        "Last month" to "last_month",
        "Search History" to "search_history",
        "Select a Forum in Sidebar" to "select_a_forum_in_sidebar",
        "Select a Topic" to "select_a_topic",
        "Post by" to "post_by",
        "Filters" to "filters",
        "Hot Replies" to "hot_replies",
        "Load New Replies" to "load_new_replies",
        "Collapsed Content" to "collapsed_content",
        "Favorite Topics" to "favorite_topics",
        "Error" to "error",
        "Plain" to "plain",
        "Preview" to "preview",
        "Editor" to "editor",
        "Send" to "send",
        "Quote" to "quote",
        "Vote Up" to "vote_up",
        "Edit" to "edit",
        "Edit Signature" to "edit_signature",
        "Share" to "share",
        "Notifications" to "notifications",
        "Notifications (%lld)" to "notifications_d",
        "%lld Unread" to "d_unread",
        "All Read" to "all_read",
        "Read" to "read",
        "Unread" to "unread",
        "Mark All as Read" to "mark_all_as_read",
        "replied to your post" to "replied_to_your_post",
        "replied to your topic" to "replied_to_your_topic",
        "Your post" to "your_post",
        "received 10 more votes" to "received_10_more_votes",
        "Discard" to "discard",
        "Discard the draft?" to "discard_the_draft",
        "Save the draft by swiping down to dismiss the editor." to "save_the_draft_by_swiping_down_to_dismiss_the_editor",
        "Subject" to "subject",
        "Content" to "content",
        "Comment" to "comment",
        "Block Contents" to "block_contents",
        "Blocked" to "blocked",
        "Block Management" to "block_management",
        "Blocked Users" to "blocked_users",
        "%lld blocked users" to "d_blocked_users",
        "Topics and replies from these users are hidden." to "topics_and_replies_from_these_users_are_hidden",
        "Topics and replies hidden" to "topics_and_replies_hidden",
        "No Blocked Users" to "no_blocked_users",
        "People you block will appear here." to "people_you_block_will_appear_here",
        "Unblock" to "unblock",
        "Unblock All" to "unblock_all",
        "Unblock All Users?" to "unblock_all_users",
        "Their topics and replies will be visible again." to "their_topics_and_replies_will_be_visible_again",
        "No Block Words" to "no_block_words",
        "New word" to "new_word",
        "Settings" to "settings",
        "Reading" to "reading",
        "Resume from Last Read Floor" to "resume_from_last_read_floor",
        "Show Signature" to "show_signature",
        "Show Avatar" to "show_avatar",
        "Collapsed Style" to "collapsed_style",
        "Redact" to "redact",
        "Hidden" to "hidden",
        "Advanced" to "advanced",
        "Dim Images in Dark Mode" to "dim_images_in_dark_mode",
        "Cache Management" to "cache_management",
        "Lock Screen Rotation" to "lock_screen_rotation",
        "Image" to "image",
        "Image Cache" to "image_cache",
        "Tap an item to clear it." to "tap_an_item_to_clear_it",
        "View Image" to "view_image",
        "Share As Image" to "share_as_image",
        "Load This Page" to "load_this_page",
        "View Video" to "view_video",
        "Always Use In-App Safari" to "always_use_in_app_safari",
        "Audio" to "audio",
        "Show Topic Subject" to "show_topic_subject",
        "Append" to "append",
        "New Topic" to "new_topic",
        "View" to "view",
        "View Replies" to "view_replies",
        "User Profile" to "user_profile",
        "Author Only" to "author_only",
        "This Author Only" to "this_author_only",
        "Locate This Floor" to "locate_this_floor",
        "Topic (Cached)" to "topic_cached",
        "View Cached Topic" to "view_cached_topic",
        "Cache Loaded" to "cache_loaded",
        "About & Feedback" to "about_feedback",
        "Just now" to "just_now",
        "LumaGA Description" to "lumaga_description",
        "LumaGA Please Share" to "lumaga_please_share",
        "Support" to "support",
        "Success" to "success",
        "Draft Saved" to "draft_saved",
        "Download Location" to "download_location",
        "%@'s Topics" to "s_s_topics",
        "%@'s Posts" to "s_s_posts",
        "Posts" to "posts",
        "My Profile" to "my_profile",
        "Edit Favorites" to "edit_favorites",
        "Posting" to "posting",
        "Device Identity" to "device_identity",
        "Desktop" to "desktop",
        "Enable Zoom for Image Viewer" to "enable_zoom_for_image_viewer",
        "Order by" to "order_by",
        "Latest Replies" to "latest_replies",
        "Bad or Unsupported Post Content Format" to "bad_or_unsupported_post_content_format",
        "Default Order" to "default_order",
        "Recommended Topics" to "recommended_topics",
        "Topped Topic" to "topped_topic",
        "Copy" to "copy",
        "Open in Browser" to "open_in_browser",
        "Short Messages" to "short_messages",
        "No Short Messages" to "no_short_messages",
        "Short Message" to "short_message",
        "%lld new unread notifications" to "d_new_unread_notifications",
        "Replies Chain" to "replies_chain",
        "Goto Topic" to "goto_topic",
        "Copy Title" to "copy_title",
        "Short Message Details" to "short_message_details",
        "Appearance" to "appearance",
        "Custom Appearance" to "custom_appearance",
        "Theme Color" to "theme_color",
        "Use Dynamic Colors" to "use_dynamic_colors",
        "Use wallpaper colors, except in Classic mode." to "dynamic_colors_description",
        "Prefer High Refresh Rate" to "prefer_high_refresh_rate",
        "Hide Notification Shortcut" to "hide_notification_shortcut",
        "New Short Message" to "new_short_message",
        "Send To" to "send_to",
        "Separate multiple users with space." to "separate_multiple_users_with_space",
        "sent you a short message" to "sent_you_a_short_message",
        "mentioned you in a post" to "mentioned_you_in_a_post",
        "mentioned you in a topic" to "mentioned_you_in_a_topic",
        "Goto %@" to "goto_s",
        "Goto Forum" to "goto_forum",
        "Color Scheme" to "color_scheme",
        "Auto" to "auto",
        "Light" to "light",
        "Dark" to "dark",
        "Search Results" to "search_results",
        "Search Topics" to "search_topics",
        "Topic %@" to "topic_s",
        "Floor" to "floor",
        "Floor %lld" to "floor_d",
        "[Floor %lld]" to "floor_bracketed",
        "Fame:" to "fame_colon",
        "Posts:" to "posts_colon",
        "Page" to "page",
        "Jump" to "jump",
        "Jump to..." to "jump_to",
        "Type here..." to "type_here",
        "First" to "first",
        "Last" to "last",
        "Load Page %lld" to "load_page_d",
        "Loading Previous Page" to "loading_previous_page",
        "Accounts" to "accounts",
        "Add Account" to "add_account",
        "Multiple Accounts" to "multiple_accounts",
        "Account Switched" to "account_switched",
        "Select Text" to "select_text",
        "Text Selection" to "text_selection",
        "Copy All" to "copy_all",
        "Empty" to "empty",
        "Cached Topic" to "cached_topic",
        "Search \"%@\" in..." to "search_s_in",
        "All Topics" to "all_topics",
        "All Users" to "all_users",
        "Search" to "search",
        "User" to "user",
        "Forum Search" to "forum_search",
        "Topic Search" to "topic_search",
        "Current Forum" to "current_forum",
        "Search Content" to "search_content",
        "User Search" to "user_search",
        "Anonymous" to "anonymous",
        "Anonymous User" to "anonymous_user",
        "Clock in" to "clock_in",
        "Clock In" to "clock_in",
        "Clocked in Successfully" to "clocked_in_successfully",
        "Clocked In" to "clocked_in",
        "Clock Stats" to "clock_stats",
        "Clock Streak" to "clock_streak",
        "Clock Streak Days" to "clock_streak_days",
        "Clock Total Days" to "clock_total_days",
        "Clock Gold" to "clock_gold",
        "Clock Silver" to "clock_silver",
        "Clock Copper" to "clock_copper",
        "Clock N Coin" to "clock_n_coin",
        "Laboratory" to "laboratory",
        "Enable Clock In" to "enable_clock_in",
        "Auto Clock In on Launch" to "auto_clock_in_on_launch",
        "General" to "general",
        "Topic List" to "topic_list",
        "Topic Details" to "topic_details",
        "Post Row" to "post_row",
        "LumaGA Link" to "lumaga_link",
        "NGA Link" to "nga_link",
        "Screenshot" to "screenshot",
        "Failed to render screenshot." to "failed_to_render_screenshot",
        "Navigated to Link" to "navigated_to_link",
        "Not a valid NGA or LumaGA link in the pasteboard." to "not_a_valid_nga_or_lumaga_link_in_the_pasteboard",
        "Invalid URL" to "invalid_url",
        "Navigate" to "navigate",
        "Connection" to "connection",
        "Backend" to "backend",
        "LumaGA Backend" to "lumaga_backend",
        "Upload Image" to "upload_image",
        "Data" to "data",
        "All" to "all",
        "Topic Histories" to "topic_histories",
        "Topic Cache" to "topic_cache",
        "Are you sure to clear the cache?" to "are_you_sure_to_clear_the_cache",
        "This will take a while." to "this_will_take_a_while",
        "%llu items" to "llu_items",
        "Clear" to "clear",
        "View Attachment" to "view_attachment",
        "Attachments" to "attachments",
        "Attachments (%lld)" to "attachments_d",
        "LumaGA Development" to "lumaga_development",
        "Post Appearance" to "post_appearance",
        "Dummy User" to "dummy_user",
        "This is a post." to "this_is_a_post",
        "This is a comment." to "this_is_a_comment",
        "This is a signature." to "this_is_a_signature",
        "Collapsed here." to "collapsed_here",
        "Swipe Trigger Edge" to "swipe_trigger_edge",
        "Primary Swipe Action" to "primary_swipe_action",
        "Leading" to "leading",
        "Trailing" to "trailing",
        "Show User Details" to "show_user_details",
        "Show User Register Date" to "show_user_register_date",
        "Date Display" to "date_display",
        "Detailed" to "detailed",
        "Time Ago" to "time_ago",
        "Topic List Style" to "topic_list_style",
        "Topic Details Style" to "topic_details_style",
        "Author Info" to "author_info",
        "Show Author Indicator" to "show_author_indicator",
        "Quick Page Jump" to "quick_page_jump",
        "Unfavorited" to "unfavorited",
        "Unfavorite failed" to "unfavorite_failed",
        "(OP)" to "op_label",
        "Personal Center" to "personal_center",
        "Mode" to "mode",
        "Participants" to "participants",
        "List Style" to "list_style",
        "Compact" to "compact",
        "Modern" to "modern",
        "Report" to "report",
        "Block This User" to "block_this_user",
        "Unblock This User" to "unblock_this_user",
        "Auto Open in Browser when Banned" to "auto_open_in_browser_when_banned",
        "NGA Workaround" to "nga_workaround",
        "Special" to "special",
        "Custom" to "custom",
        "Custom User-Agent" to "custom_user_agent",
        "Tag" to "tag",
        "Add Tag" to "add_tag",
        "Untitled" to "untitled",
        "Larger Font" to "larger_font",
        "Unknown" to "unknown",
        "Auto Refreshed" to "auto_refreshed",
        "Unlock Plus" to "unlock_plus",
        "Plus Unlocked" to "plus_unlocked",
        "Plus Thanks" to "plus_thanks",
        "Plus Explanation" to "plus_explanation",
        "Try Plus" to "try_plus",
        "You're enjoying a Plus trial" to "you_re_enjoying_a_plus_trial",
        "Trial ends on %@" to "trial_ends_on_s",
        "Your Plus trial has expired" to "your_plus_trial_has_expired",
        "Products unavailable. Please try again later." to "products_unavailable_please_try_again_later",
        "Restore Purchases" to "restore_purchases",
        "Redeem Code" to "redeem_code",
        "We couldn't verify your purchase. Please try again." to "we_couldn_t_verify_your_purchase_please_try_again",
        "\"%@\" is a Plus feature" to "s_is_a_plus_feature",
        "Unlock LumaGA Plus to access this feature." to "unlock_lumaga_plus_to_access_this_feature",
        "Tap to unlock LumaGA Plus to access this feature" to "tap_to_unlock_lumaga_plus_to_access_this_feature",
        "Show Plus in Title" to "show_plus_in_title",
        "LumaGA Main Menu" to "lumaga_main_menu",
        "Sign in to NGA and discover more features here." to "sign_in_to_nga_and_discover_more_features_here",
        "Continue" to "s_continue",
        "Current Version" to "current_version",
        "Check out Plus" to "check_out_plus",
        "Expand All Categories" to "expand_all_categories",
        "Collapse All Categories" to "collapse_all_categories",
        "Done" to "done",
        "Reply not found. It may have been deleted." to "reply_not_found_it_may_have_been_deleted",
        "View and Manage Subforums" to "view_and_manage_subforums",
        "Subforum Tip" to "subforum_tip",
        "Folders" to "folders",
        "All Folders" to "all_folders",
        "Default" to "s_default",
        "Default Folder" to "default_folder",
        "Make Default" to "make_default",
        "Make Default Folder" to "make_default_folder",
        "Delete Folder..." to "delete_folder",
        "Delete" to "delete",
        "Delete the folder and all its topics?" to "delete_the_folder_and_all_its_topics",
        "Rename" to "rename",
        "Rename Folder..." to "rename_folder",
        "Folder Name" to "folder_name",
        "Multiple Favorite Folders" to "multiple_favorite_folders",
        "New Folder..." to "new_folder",
        "Unnamed Folder" to "unnamed_folder",
        "Add to New Folder" to "add_to_new_folder",
        "Resume Reading Progress" to "resume_reading_progress",
        "Refresh Button" to "refresh_button",
        "Blocked Topics Style" to "blocked_topics_style",
        "Redact Subject" to "redact_subject",
        "Hide Topic" to "hide_topic",
        "Disabled" to "disabled",
        "Last Read Floor" to "last_read_floor",
        "Highest Read Floor" to "highest_read_floor",
        "Primary" to "primary",
        "Secondary" to "secondary",
        "Only Web API" to "only_web_api",
        "Web API Explained" to "web_api_explained",
        "Always Share Image as File" to "always_share_image_as_file",
        "Show Forum Shortcuts" to "show_forum_shortcuts",
        "Search Bar Position" to "search_bar_position",
        "Top" to "top",
        "Bottom" to "bottom",
        "Album" to "album",
        "Multicolor Subject" to "multicolor_subject",
        "Sync Favorites" to "sync_favorites",
        "Use NGA Classic Icon" to "use_nga_classic_icon",
        "Compact Topic List" to "compact_topic_list",
        "Back" to "back",
        "Sync Favorite Forums" to "sync_favorite_forums",
        "LumaGA Login Notice" to "lumaga_login_notice",
        "All Plus Features" to "all_plus_features",
        "Comment on posts in all topics." to "comment_on_posts_in_all_topics",
        "Post, quote, reply, comment, and create new topics anonymously." to "post_quote_reply_comment_and_create_new_topics_anonymously",
        "Create new topics in all forums." to "create_new_topics_in_all_forums",
        "View hot topics from the past 24 hours, week, or month." to "view_hot_topics_from_the_past_24_hours_week_or_month",
        "Send and receive short messages with other users." to "send_and_receive_short_messages_with_other_users",
        "View your footprint of topics you have explored." to "view_your_footprint_of_topics_you_have_explored",
        "Check posts and replies from a specific author in a topic." to "check_posts_and_replies_from_a_specific_author_in_a_topic",
        "Jump to arbitrary floor or page in a topic." to "jump_to_arbitrary_floor_or_page_in_a_topic",
        "Log in and switch between multiple accounts." to "log_in_and_switch_between_multiple_accounts",
        "View user profiles, with their posts and replies." to "view_user_profiles_with_their_posts_and_replies",
        "Full access to customizing the appearance of LumaGA." to "full_access_to_customizing_the_appearance_of_lumaga",
        "Block contents from specific users, or with specific keywords." to "block_contents_from_specific_users_or_with_specific_keywords",
        "Organize favorite topics into multiple folders." to "organize_favorite_topics_into_multiple_folders",
        "Resume reading progress from where you left off." to "resume_reading_progress_from_where_you_left_off",
        "Sync favorite forums across devices." to "sync_favorite_forums_across_devices",
        "More Features in the Future" to "more_features_in_the_future",
        "Plus More Feature" to "plus_more_feature",
        // `ServiceError::MngaInternal` still stringifies as "MNGA" inside the
        // prebuilt liblogic.so; localize it rather than rebuild the library.
        "MNGA" to "lumaga_error_kind",
        "Error Response" to "error_response",
        "Missing Field" to "missing_field",
        "Network Connection" to "network_connection",
        "XML Parse" to "xml_parse",
        "JSON Parse" to "json_parse",
        "XPath Resolve" to "xpath_resolve",
        "Text Parse" to "text_parse",
        "URL Parse" to "url_parse",
        "Backend Panic" to "backend_panic",
        "Red" to "red",
        "Orange" to "orange",
        "Yellow" to "yellow",
        "Green" to "green",
        "Mint" to "mint",
        "Teal" to "teal",
        "Cyan" to "cyan",
        "Blue" to "blue",
        "Indigo" to "indigo",
        "Purple" to "purple",
        "Pink" to "pink",
        "Brown" to "brown",
        "Gray" to "gray",
        "About" to "about",
        "Check for Updates" to "check_for_updates",
        "You're up to date" to "you_re_up_to_date",
        "New Version Available" to "new_version_available",
        "Download & Install" to "download_and_install",
        "Later" to "later",
        "Downloading Update" to "downloading_update",
        "Download Complete" to "download_complete",
        "Install" to "install",
        "Permission Required" to "permission_required",
        "Allow LumaGA to install apps, then tap Install again." to "allow_install_apps",
        "Open Settings" to "open_settings",
        "Update Check Failed" to "update_check_failed",
        "Download Failed" to "download_failed",
        "This release has no APK to download." to "release_has_no_apk",
        "Release Page" to "release_page",
        "Release Notes" to "release_notes",
        "Retry" to "retry",
        "Close" to "close",
        "OK" to "ok",
        "Source Code" to "source_code",
        "An NGA forum client, ported from MNGA." to "an_nga_forum_client"
    )
}
